### ISSUE TITLE
Rx flatMap i switchMap

### ISSUE THREAD

**Issue by bagy94** [DavorStajcer/FactoryNewsProject#8]
https://github.com/DavorStajcer/FactoryNewsProject/blob/52b508d56c7f0260f94249e35b35d938b8e7d22e/app/src/main/java/hr/davor_news/factory/news_activity/NewsActivityViewModel.kt#L42

Prouciti {{Rx}}.flatMap i .switchMap

**Comment by matijasolic** [comment]
https://github.com/DavorStajcer/FactoryNewsProject/blob/907fe15aaa8fe3be5acbf8e5a3f126b29c238fba/app/src/main/java/hr/davor_news/factory/fragments/displaying_all_articles/DisplayingAllArticlesViewModel.kt#L26 
Navedeni kod i dalje ne održava željeno ponašanje -> " u koliko je prošlo više od 5 min potrebno je povući nove podatke"
